version: "3"
services:
  pic-bot:
    image: adevjoe/pic-bot:latest
    container_name: pic-bot
    volumes:
      - ./.gallery-dl.conf:/etc/gallery-dl.conf
      - ./gallery-dl:/gallery-dl
      - ./cache:/root/.cache/gallery-dl
    environment:
      - BOT_TOKEN=
      - CHAT_ID=
      - WELCOME_MESSAGE=
    restart: always
